"use client"

import { useState } from "react"
import { ArrowLeft, Globe, Atom, Database, Layers, Network, Cpu, Zap, Binary, Settings } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

export function ReferencePage({ onBack, onSysAdmin }: { onBack: () => void; onSysAdmin: () => void }) {
  const [activeSection, setActiveSection] = useState<string>("introduction")
  const sections = [
    { id: "introduction", label: "Introduction", icon: Globe },
    { id: "foundations", label: "Foundations", icon: Atom },
    { id: "aio-definition", label: "AIO Definition", icon: Database },
    { id: "semantic-layer", label: "Semantic Layer", icon: Layers },
    { id: "hyper-semantic", label: "Hyper-Semantic Model", icon: Network },
    { id: "information-physics", label: "Information Physics", icon: Cpu },
    { id: "llm-implications", label: "LLM Implications", icon: Zap },
    { id: "future", label: "Future Directions", icon: Binary },
  ]

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border bg-card">
        <div className="max-w-6xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Button variant="ghost" size="sm" onClick={onBack} className="gap-2"><ArrowLeft className="w-4 h-4" />Back</Button>
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-lg bg-primary flex items-center justify-center"><BookOpen className="w-5 h-5 text-primary-foreground" /></div>
                <h1 className="text-xl font-bold text-foreground">Information Physics Reference</h1>
              </div>
            </div>
            <Button variant="outline" size="sm" onClick={onSysAdmin} className="gap-2"><Settings className="w-4 h-4" />System Admin</Button>
          </div>
        </div>
      </header>
      <main className="max-w-6xl mx-auto px-6 py-8">
        <div className="grid lg:grid-cols-[240px_1fr] gap-8">
          <nav className="space-y-1">
            {sections.map((section) => { const Icon = section.icon; return (
              <button key={section.id} onClick={() => setActiveSection(section.id)} className={`w-full flex items-center gap-3 px-3 py-2 rounded-lg text-sm transition-colors ${activeSection === section.id ? "bg-primary/10 text-primary font-medium" : "text-muted-foreground hover:bg-accent hover:text-foreground"}`}>
                <Icon className="w-4 h-4" />{section.label}
              </button>
            )})}
          </nav>
          <div className="space-y-6">
            {activeSection === "introduction" && (<Card><CardHeader><CardTitle className="flex items-center gap-2"><Globe className="w-5 h-5" />Introduction to Information Physics</CardTitle></CardHeader><CardContent className="space-y-4 text-sm text-muted-foreground leading-relaxed"><p>Information Physics is a new theoretical framework that treats information as a fundamental physical quantity, on par with matter and energy. This standard model proposes that all meaningful data can be decomposed into Associated Information Objects (AIOs) - discrete, self-describing units that capture both content and context.</p><p>The framework challenges the traditional view of data as passive records stored in application-specific formats. Instead, it posits that information has intrinsic properties and behaviors that can be studied, modeled, and leveraged independently of any particular software system.</p><p>This reference provides an overview of the key concepts, definitions, and implications of the Information Physics Standard Model.</p></CardContent></Card>)}
            {activeSection === "foundations" && (<Card><CardHeader><CardTitle className="flex items-center gap-2"><Atom className="w-5 h-5" />Theoretical Foundations</CardTitle></CardHeader><CardContent className="space-y-4 text-sm text-muted-foreground leading-relaxed"><h4 className="text-foreground font-medium">The Information Axiom</h4><p>At the core of Information Physics is the axiom that information is not merely a description of reality but a constituent of it. Just as physics studies the fundamental forces and particles of the universe, Information Physics studies the fundamental units and interactions of meaningful data.</p><h4 className="text-foreground font-medium mt-4">Application Independence</h4><p>Traditional data formats (SQL tables, JSON documents, XML trees) are designed to serve specific applications. Information Physics argues that this application-dependence is an artificial constraint that limits our ability to understand and leverage information.</p><h4 className="text-foreground font-medium mt-4">Semantic Completeness</h4><p>An AIO is semantically complete - it contains all the context needed to interpret its meaning without reference to external schemas, documentation, or application logic. This is achieved through the key-value pair structure where the key provides the semantic label and the value provides the data.</p></CardContent></Card>)}
            {activeSection === "aio-definition" && (<Card><CardHeader><CardTitle className="flex items-center gap-2"><Database className="w-5 h-5" />Associated Information Object (AIO)</CardTitle></CardHeader><CardContent className="space-y-4 text-sm text-muted-foreground leading-relaxed"><h4 className="text-foreground font-medium">Formal Definition</h4><p>An Associated Information Object (AIO) is a single-line string composed of one or more bracketed elements, where each element takes the form <code className="bg-muted px-1 rounded">[Key.Value]</code>. The concatenation of all elements forms a complete, self-describing information object.</p><h4 className="text-foreground font-medium mt-4">Properties</h4><ul className="list-disc list-inside space-y-2"><li><strong>Atomicity:</strong> Each AIO represents one indivisible unit of associated information</li><li><strong>Self-Description:</strong> Keys provide semantic meaning; no external schema required</li><li><strong>Linearity:</strong> Single-line format ensures simple parsing and streaming</li><li><strong>Composability:</strong> AIOs can be combined to form larger information structures</li><li><strong>Provenance:</strong> Metadata elements track the origin and timestamp of data</li></ul><h4 className="text-foreground font-medium mt-4">Element Types</h4><ul className="list-disc list-inside space-y-2"><li><strong>Metadata Elements:</strong> OriginalCSV, FileDate, FileTime - describe the source</li><li><strong>Data Elements:</strong> Column-value pairs from the original data</li></ul></CardContent></Card>)}
            {activeSection === "semantic-layer" && (<Card><CardHeader><CardTitle className="flex items-center gap-2"><Layers className="w-5 h-5" />The Semantic Layer</CardTitle></CardHeader><CardContent className="space-y-4 text-sm text-muted-foreground leading-relaxed"><p>The Semantic Layer is the conceptual framework that emerges when collections of AIOs are analyzed for shared elements and patterns. It represents the web of meaning that connects individual information objects.</p><h4 className="text-foreground font-medium mt-4">Element Matching</h4><p>When two or more AIOs share an identical element (same key and value), they are semantically linked. This linkage is inherent in the data and requires no external join tables, foreign keys, or relationship definitions.</p><h4 className="text-foreground font-medium mt-4">Emergent Relationships</h4><p>As more AIOs are added to a collection, the semantic layer grows organically. Relationships emerge naturally from shared elements rather than being predefined by a database administrator.</p><h4 className="text-foreground font-medium mt-4">Cross-Domain Discovery</h4><p>Because AIOs are application-agnostic, the semantic layer can reveal connections between data from entirely different domains - connections that traditional siloed databases would never surface.</p></CardContent></Card>)}
            {activeSection === "hyper-semantic" && (<Card><CardHeader><CardTitle className="flex items-center gap-2"><Network className="w-5 h-5" />The Hyper-Semantic Model</CardTitle></CardHeader><CardContent className="space-y-4 text-sm text-muted-foreground leading-relaxed"><p>The Hyper-Semantic Model extends the basic semantic layer into a multi-dimensional space of meaning. While traditional semantics deals with the meaning of individual terms, hyper-semantics captures the emergent meaning that arises from the interaction of multiple AIOs.</p><h4 className="text-foreground font-medium mt-4">Dimensions of Meaning</h4><ul className="list-disc list-inside space-y-2"><li><strong>Element Frequency:</strong> How often a particular element appears across AIOs</li><li><strong>Co-occurrence:</strong> Which elements tend to appear together</li><li><strong>Exclusivity:</strong> Elements that uniquely identify specific AIOs or clusters</li><li><strong>Temporal Patterns:</strong> How element distributions change over time</li></ul><h4 className="text-foreground font-medium mt-4">Information Density</h4><p>The hyper-semantic model introduces the concept of information density - a measure of how much semantic content is packed into a given AIO or collection. Higher density indicates richer, more interconnected information.</p></CardContent></Card>)}
            {activeSection === "information-physics" && (<Card><CardHeader><CardTitle className="flex items-center gap-2"><Cpu className="w-5 h-5" />Information Physics Principles</CardTitle></CardHeader><CardContent className="space-y-4 text-sm text-muted-foreground leading-relaxed"><h4 className="text-foreground font-medium">Conservation of Information</h4><p>When data is converted from CSV to AIO format, no information is lost. The transformation is lossless and reversible. This reflects the principle that information, like energy, is conserved through transformations.</p><h4 className="text-foreground font-medium mt-4">Information Gravity</h4><p>AIOs with shared elements naturally cluster together in the semantic layer, much like massive objects attract each other through gravity. The more shared elements between AIOs, the stronger their semantic attraction.</p><h4 className="text-foreground font-medium mt-4">Semantic Entropy</h4><p>As information flows through systems, it tends toward increasing entropy - data becomes fragmented, duplicated, and disconnected. The AIO format counteracts this by maintaining semantic coherence at the object level.</p><h4 className="text-foreground font-medium mt-4">Observation Effect</h4><p>The act of querying or analyzing AIOs through the semantic processor can reveal relationships that were always present but not previously observed, paralleling the observation effect in quantum physics.</p></CardContent></Card>)}
            {activeSection === "llm-implications" && (<Card><CardHeader><CardTitle className="flex items-center gap-2"><Zap className="w-5 h-5" />Implications for Large Language Models</CardTitle></CardHeader><CardContent className="space-y-4 text-sm text-muted-foreground leading-relaxed"><p>The hyper-semantic model built on AIOs has profound implications for the next generation of Large Language Models (LLMs).</p><h4 className="text-foreground font-medium mt-4">Enhanced Understanding</h4><p>LLMs trained on AIO-structured data would have access to explicit semantic relationships rather than having to infer them from unstructured text. This could dramatically improve comprehension and reduce hallucination.</p><h4 className="text-foreground font-medium mt-4">Grounded Reasoning</h4><p>By operating on self-describing information objects, LLMs could perform more grounded reasoning with clear provenance chains. Every conclusion could be traced back to specific AIO elements.</p><h4 className="text-foreground font-medium mt-4">Cross-Domain Transfer</h4><p>The application-agnostic nature of AIOs means that knowledge gained in one domain automatically transfers to others. An LLM that understands [City.New York] in a personnel context equally understands it in a logistics context.</p><h4 className="text-foreground font-medium mt-4">Semantic Search</h4><p>Instead of keyword matching or vector similarity, AIO-based search operates on exact semantic elements, enabling precise retrieval without the ambiguity of natural language queries.</p></CardContent></Card>)}
            {activeSection === "future" && (<Card><CardHeader><CardTitle className="flex items-center gap-2"><Binary className="w-5 h-5" />Future Directions</CardTitle></CardHeader><CardContent className="space-y-4 text-sm text-muted-foreground leading-relaxed"><h4 className="text-foreground font-medium">Expanded Format Support</h4><p>While the current implementation converts CSV to AIO, future versions will support conversion from JSON, XML, SQL databases, APIs, and other structured data sources.</p><h4 className="text-foreground font-medium mt-4">Distributed AIO Networks</h4><p>AIOs could be shared across distributed networks, creating a global semantic layer that transcends organizational boundaries while maintaining data sovereignty.</p><h4 className="text-foreground font-medium mt-4">Real-Time Processing</h4><p>Stream processing of AIOs would enable real-time semantic analysis, allowing systems to detect patterns and relationships as data flows rather than in batch processing.</p><h4 className="text-foreground font-medium mt-4">Semantic Compression</h4><p>Frequently occurring elements across AIOs could be compressed using semantic dictionaries, reducing storage requirements while preserving full meaning.</p><h4 className="text-foreground font-medium mt-4">AIO Algebra</h4><p>A formal algebra for AIO operations (union, intersection, difference, projection) would provide a mathematical foundation for information manipulation comparable to relational algebra for databases.</p></CardContent></Card>)}
          </div>
        </div>
      </main>
      <footer className="border-t border-border mt-16"><div className="max-w-6xl mx-auto px-6 py-6 text-center"><p className="text-sm text-muted-foreground">InformationPhysics (informationphysics.ai) - InformationPhysics.ai</p></div></footer>
    </div>
  )
}
